# dnsmasq assigns local IP addresses (DHCP) and resolves DNS queries.

interface=wlan0
bind-interfaces

dhcp-range=192.168.2.100,192.168.2.200,24h
dhcp-option=3,192.168.2.1
dhcp-option=6,192.168.2.1

# Send everything to dnsCrypt-Proxy.
no-resolv
server=127.0.0.1#5353
