# dnsCrypt encrypts incoming DNS queries in plain text.

listen_addresses = ['127.0.0.1:5353']

server_names = ['cloudflare', 'quad9-dnscrypt-ip4-nofilter-pri']

# Ad blocking.
# The list is installed in the install script.
[blocked_names]
  blocked_names_file = '/etc/dnscrypt-proxy/blocked-names.txt'

[sources]
  [sources.public-resolvers]
  
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md']

  cache_file = '/var/cache/dnscrypt-proxy/public-resolvers.md'

  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'

  refresh_delay = 72

[query_log]
  file = '/var/log/dnscrypt-proxy/query.log'
